USE [master]
GO

/****** Object:  Database [Murray]    Script Date: 22/02/2023 07:52:43 p. m. ******/
CREATE DATABASE [Murray]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Murray', FILENAME = N'D:\Apps\Universidad\SQL\SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Murray.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Murray_log', FILENAME = N'D:\Apps\Universidad\SQL\SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Murray_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Murray].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Murray] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Murray] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Murray] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Murray] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Murray] SET ARITHABORT OFF 
GO

ALTER DATABASE [Murray] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Murray] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Murray] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Murray] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Murray] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Murray] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Murray] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Murray] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Murray] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Murray] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Murray] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Murray] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Murray] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Murray] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Murray] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Murray] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Murray] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Murray] SET RECOVERY FULL 
GO

ALTER DATABASE [Murray] SET  MULTI_USER 
GO

ALTER DATABASE [Murray] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Murray] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Murray] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Murray] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Murray] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Murray] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Murray] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Murray] SET  READ_WRITE 
GO


