USE [master]
GO

/****** Object:  Database [DWMurray]    Script Date: 22/02/2023 10:05:02 p. m. ******/
CREATE DATABASE [DWMurray]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DWMurray', FILENAME = N'D:\Apps\Universidad\SQL\SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DWMurray.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DWMurray_log', FILENAME = N'D:\Apps\Universidad\SQL\SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DWMurray_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DWMurray].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DWMurray] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DWMurray] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DWMurray] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DWMurray] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DWMurray] SET ARITHABORT OFF 
GO

ALTER DATABASE [DWMurray] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DWMurray] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DWMurray] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DWMurray] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DWMurray] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DWMurray] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DWMurray] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DWMurray] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DWMurray] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DWMurray] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DWMurray] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DWMurray] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DWMurray] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DWMurray] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DWMurray] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DWMurray] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DWMurray] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DWMurray] SET RECOVERY FULL 
GO

ALTER DATABASE [DWMurray] SET  MULTI_USER 
GO

ALTER DATABASE [DWMurray] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DWMurray] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DWMurray] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DWMurray] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DWMurray] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DWMurray] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DWMurray] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DWMurray] SET  READ_WRITE 
GO


